package main

import (
	"github.com/go-chi/chi/v5"
	_ "github.com/softbakeio/ote-api/docs" // docs is generated by Swag CLI, you have to import it.
	httpSwagger "github.com/swaggo/http-swagger"

	"log"
	"net/http"
)

// @title Swagger OTE electricity data API
// @version 1.0
// @description This is a OTE electricity data API server which provide 24 hours electricity data
// and evaluate user value with current electricity value on the marker
// @termsOfService http://swagger.io/terms/
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
func main()  {

	oteApi := NewOteApi()

	r := chi.NewRouter()
	//setup handler routes
	r.Method("GET", "/ote/electricity", oteApi.GetElectricityOteData())
	r.Method("POST", "/ote/electricity/evaluate", oteApi.EvaluateElectricityValue())

	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8080/swagger/doc.json"), //The url pointing to API definition
	))

	log.Println("Starting server at port 8080")

	if err := http.ListenAndServe(":8080", r); err != nil {
		log.Fatal(err)
	}
}